name       : libmwaw
version    : 0.3.11
release    : 3
source     :
    - http://internode.dl.sourceforge.net/project/libmwaw/libmwaw/libmwaw-0.3.11/libmwaw-0.3.11.tar.xz : 4b483a196bbe82bc0f7cb4cdf70ef1cedb91139bd2e037eabaed4a4d6ed2299a
license    :
    - LGPL-2.1
    - MPL-2.0
component  : programming
summary    : Convert many pre-OSX MAC formats
description: |
    Libmwaw is a new project for converting many pre-OSX MAC text formats, some graphic formats and some spreadsheet formats.
builddeps  :
    - pkgconfig(librevenge-0.0)
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
