name       : libmwaw
version    : 0.3.10
release    : 2
source     :
    - http://internode.dl.sourceforge.net/project/libmwaw/libmwaw/libmwaw-0.3.10/libmwaw-0.3.10.tar.xz : b246a0c15fcf98076f2a1f2cf4d44a714f5c8eb39690442fc7fbbd01fa34f220
license    :
    - LGPL-2.1
    - MPL-2.0
component  : programming
summary    : Convert many pre-OSX MAC formats
description: |
    Libmwaw is a new project for converting many pre-OSX MAC text formats, some graphic formats and some spreadsheet formats.
builddeps  :
    - pkgconfig(librevenge-0.0)
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
