name       : libmwaw
version    : 0.3.20
release    : 6
source     :
    - https://sourceforge.net/projects/libmwaw/files/libmwaw/libmwaw-0.3.20/libmwaw-0.3.20.tar.xz : 14c38b06214f277ccd1450e22e6e32648955018d7695896bc560165748c8cd21
homepage   : https://sourceforge.net/projects/libmwaw/
license    :
    - LGPL-2.1-or-later
    - MPL-2.0
component  : programming
summary    : Import library for legacy Mac documents
description: |
    libmwaw contains import filters for many old Macintosh text document formats (MacWrite, ClarisWorks, ... ) and for some graphic, spreadsheet and presentation formats.
builddeps  :
    - pkgconfig(librevenge-0.0)
setup      : |
    %configure --disable-werror
build      : |
    %make
install    : |
    %make_install
