name       : libmwaw
version    : 0.3.21
release    : 7
source     :
    - https://sourceforge.net/projects/libmwaw/files/libmwaw/libmwaw-0.3.21/libmwaw-0.3.21.tar.xz : e8750123a78d61b943cef78b7736c8a7f20bb0a649aa112402124fba794fc21c
homepage   : https://sourceforge.net/projects/libmwaw/
license    :
    - LGPL-2.1-or-later
    - MPL-2.0
component  : programming
summary    : Import library for legacy Mac documents
description: |
    libmwaw contains import filters for many old Macintosh text document formats (MacWrite, ClarisWorks, ... ) and for some graphic, spreadsheet and presentation formats.
builddeps  :
    - pkgconfig(librevenge-0.0)
setup      : |
    %configure --disable-werror
build      : |
    %make
install    : |
    %make_install
